### ISSUE TITLE
question about impelemention error : self.hparams = hparams

### ISSUE THREAD

**Issue by return-sleep** [biomedia-mira/deepscm#6]
Thanks for your great work.
when I run the code : 
`python -m deepscm.experiments.morphomnist.trainer -e SVIExperiment -m ConditionalVISEM --data_dir /path/to/data --default_root_dir /path/to/checkpoints --decoder_type fixed_var {--gpus 0}`

**some wrong happened:**
In deepscm\experiments\morphomnist\base_experiment.py 
```
Traceback (most recent call last):
  File "E:\anaconda3\envs\dscm\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "E:\anaconda3\envs\dscm\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "deepscm\deepscm\experiments\morphomnist\trainer.py", line 97, in <module>
    experiment = exp_class(hparams, model)
  File "\deepscm\deepscm\experiments\morphomnist\sem_vi\base_sem_experiment.py", 
line 270, in __init__
    super().__init__(hparams, pyro_model)
  File "deepscm\deepscm\experiments\morphomnist\base_experiment.py", line 175, in __init__
    self.hparams = hparams
  File "E:\anaconda3\envs\dscm\lib\site-packages\torch\nn\modules\module.py", line 1225, in __setattr__
    object.__setattr__(self, name, value)
AttributeError: can't set attribute
```
I'm no idea how to fix this issue. Looking forward to your reply

**Comment by aengusl** [comment]
downgrade pytorch lightning to the version given in the requirements.txts
